#!/bin/sh

sudo geth \
--datadir=$HOME/.pooh/el \
--syncmode=full \
--networkid=12301 \
--bootnodes="enode://6d59a1ce195d9251e8f5234b3dbd486cf15eeac6cb8199898af3e11b9b7f5c54e334317d1cc3ab8077360383bc08b8aa93299ccb169b55dbea59414847dbce2d@3.37.37.195:30303" \
--allow-insecure-unlock=true \
--unlock=0x997c277946420aff5ded06d0f52725b17fa1971a \
--password=./password.txt \
--mine=true \
--rpc.allow-unprotected-txs \
--metrics \
--metrics.addr=0.0.0.0 \
--metrics.port=6060 \
--miner.etherbase=0x8532654aD638Db3deE3836B22B35f7Ca707428ca \
--http \
--http.addr="0.0.0.0" \
--http.port=8545 \
--http.corsdomain="*" \
--http.api="personal,eth,net,txpool,web3" \
--http.vhosts="*" \
--ws \
--ws.port=8546 \
--ws.api="personal,eth,net,txpool,web3" \
--ws.origins="*"
